### ISSUE TITLE
Error: ns not correct in ReadBlengthGH().

### ISSUE THREAD

**Issue by nextjen92** [dekoning-lab/grand-conv#4]
I am getting the error "Error: ns not correct in ReadBlengthGH(). ns = 0, expecting 8" when I try to run mcmctree. I'm not sure what is causing this error and would appreciate help getting the program to run.
I have attached the files I am using, as well as the output from mccmtree, for reference.

[codon_sequential.phy.txt](https://github.com/dekoning-lab/grand-conv/files/5929412/codon_sequential.phy.txt)
[out_mcmctree.txt](https://github.com/dekoning-lab/grand-conv/files/5929411/out_mcmctree.txt)
[mcmctree.ctl.txt](https://github.com/dekoning-lab/grand-conv/files/5929410/mcmctree.ctl.txt)
[fossil-tree.nwk.txt](https://github.com/dekoning-lab/grand-conv/files/5929408/fossil-tree.nwk.txt)
[in.BV.txt](https://github.com/dekoning-lab/grand-conv/files/5929409/in.BV.txt)

**Comment by Tianyou96** [comment]
I also have this problem, but I don't know the reason. Do you know what caused this error?
